# Default Training Configuration for LeNet-5 MNIST

# Training hyperparameters
epochs: 5
batch_size: 64
learning_rate: 0.01
momentum: 0.9

# Optimizer settings
optimizer:
  name: sgd
  weight_decay: 0.0
  nesterov: false

# Loss function
criterion: nll_loss  # Negative Log Likelihood for log_softmax output

# Learning rate scheduler (optional)
lr_scheduler:
  enabled: false
  name: step_lr
  step_size: 30
  gamma: 0.1

# Performance settings
performance:
  precision: "32-true"  # Options: 16-mixed, bf16-mixed, 32-true
  compile_model: false
  gradient_clip_val: null
  accumulate_grad_batches: 1

# Early stopping (optional)
early_stopping:
  enabled: false
  monitor: test_loss
  patience: 10
  min_delta: 0.001

# Checkpoint settings
checkpointing:
  enabled: false
  save_top_k: 1
  monitor: test_accuracy
  mode: max
